CREATE TABLE IF NOT EXISTS ex_presidents (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name_en VARCHAR(160) NOT NULL,
  name_mr VARCHAR(160) NOT NULL,
  designation_en VARCHAR(100) NOT NULL DEFAULT 'Ex-President',
  designation_mr VARCHAR(100) NOT NULL DEFAULT 'माजी अध्यक्ष',
  image_storage_key VARCHAR(500) NULL,
  photo_original_filename VARCHAR(255) NULL,
  photo_mime_type VARCHAR(100) NULL,
  photo_file_size_bytes BIGINT UNSIGNED NULL,
  phone VARCHAR(40) NULL,
  gala_number VARCHAR(40) NULL,
  category_en VARCHAR(120) NULL,
  category_mr VARCHAR(120) NULL,
  tenure_from SMALLINT UNSIGNED NULL,
  tenure_to SMALLINT UNSIGNED NULL,
  sort_order INT NOT NULL DEFAULT 100,
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_ex_presidents_active_order (is_active, sort_order),
  INDEX idx_ex_presidents_tenure_from (tenure_from),
  INDEX idx_ex_presidents_tenure_to (tenure_to)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
