/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ChairmanRouteImport } from './routes/chairman'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as LoginRouteImport } from './routes/login'
import { Route as NoticesRouteImport } from './routes/notices'
import { Route as OwnerRouteImport } from './routes/owner'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as UpdatesRouteImport } from './routes/updates'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as AdminChangePasswordRouteImport } from './routes/admin.change-password'
import { Route as AdminCommitteeRouteImport } from './routes/admin.committee'
import { Route as AdminComplaintsRouteImport } from './routes/admin.complaints'
import { Route as AdminGalleryRouteImport } from './routes/admin.gallery'
import { Route as AdminHelpRouteImport } from './routes/admin.help'
import { Route as AdminMobileRequestsRouteImport } from './routes/admin.mobile-requests'
import { Route as AdminNoticesRouteImport } from './routes/admin.notices'
import { Route as AdminPostsRouteImport } from './routes/admin.posts'
import { Route as AdminRegistrationsRouteImport } from './routes/admin.registrations'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminUpdatesRouteImport } from './routes/admin.updates'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as OwnerChangePasswordRouteImport } from './routes/owner.change-password'
import { Route as OwnerComplaintsRouteImport } from './routes/owner.complaints'
import { Route as OwnerGalaRouteImport } from './routes/owner.gala'
import { Route as OwnerHelpRouteImport } from './routes/owner.help'
import { Route as OwnerMobileChangeRouteImport } from './routes/owner.mobile-change'
import { Route as OwnerNewComplaintRouteImport } from './routes/owner.new-complaint'
import { Route as OwnerNoticesRouteImport } from './routes/owner.notices'
import { Route as OwnerNotificationsRouteImport } from './routes/owner.notifications'
import { Route as OwnerPostRouteImport } from './routes/owner.post'
import { Route as OwnerProfileRouteImport } from './routes/owner.profile'
import { Route as OwnerSharedPostsRouteImport } from './routes/owner.shared-posts'
import { Route as OwnerUpdatesRouteImport } from './routes/owner.updates'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ChairmanRoute = ChairmanRouteImport.update({
  id: '/chairman',
  path: '/chairman',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticesRoute = NoticesRouteImport.update({
  id: '/notices',
  path: '/notices',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerRoute = OwnerRouteImport.update({
  id: '/owner',
  path: '/owner',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const UpdatesRoute = UpdatesRouteImport.update({
  id: '/updates',
  path: '/updates',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRoute,
} as any)
const AdminChangePasswordRoute = AdminChangePasswordRouteImport.update({
  id: '/change-password',
  path: '/change-password',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCommitteeRoute = AdminCommitteeRouteImport.update({
  id: '/committee',
  path: '/committee',
  getParentRoute: () => AdminRoute,
} as any)
const AdminComplaintsRoute = AdminComplaintsRouteImport.update({
  id: '/complaints',
  path: '/complaints',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGalleryRoute = AdminGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHelpRoute = AdminHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMobileRequestsRoute = AdminMobileRequestsRouteImport.update({
  id: '/mobile-requests',
  path: '/mobile-requests',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNoticesRoute = AdminNoticesRouteImport.update({
  id: '/notices',
  path: '/notices',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPostsRoute = AdminPostsRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRegistrationsRoute = AdminRegistrationsRouteImport.update({
  id: '/registrations',
  path: '/registrations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUpdatesRoute = AdminUpdatesRouteImport.update({
  id: '/updates',
  path: '/updates',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const OwnerChangePasswordRoute = OwnerChangePasswordRouteImport.update({
  id: '/change-password',
  path: '/change-password',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerComplaintsRoute = OwnerComplaintsRouteImport.update({
  id: '/complaints',
  path: '/complaints',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerGalaRoute = OwnerGalaRouteImport.update({
  id: '/gala',
  path: '/gala',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerHelpRoute = OwnerHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerMobileChangeRoute = OwnerMobileChangeRouteImport.update({
  id: '/mobile-change',
  path: '/mobile-change',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerNewComplaintRoute = OwnerNewComplaintRouteImport.update({
  id: '/new-complaint',
  path: '/new-complaint',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerNoticesRoute = OwnerNoticesRouteImport.update({
  id: '/notices',
  path: '/notices',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerNotificationsRoute = OwnerNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerPostRoute = OwnerPostRouteImport.update({
  id: '/post',
  path: '/post',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerProfileRoute = OwnerProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerSharedPostsRoute = OwnerSharedPostsRouteImport.update({
  id: '/shared-posts',
  path: '/shared-posts',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerUpdatesRoute = OwnerUpdatesRouteImport.update({
  id: '/updates',
  path: '/updates',
  getParentRoute: () => OwnerRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/chairman': typeof ChairmanRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/login': typeof LoginRoute
  '/notices': typeof NoticesRoute
  '/owner': typeof OwnerRouteWithChildren
  '/register': typeof RegisterRoute
  '/updates': typeof UpdatesRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/change-password': typeof AdminChangePasswordRoute
  '/admin/committee': typeof AdminCommitteeRoute
  '/admin/complaints': typeof AdminComplaintsRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/help': typeof AdminHelpRoute
  '/admin/mobile-requests': typeof AdminMobileRequestsRoute
  '/admin/notices': typeof AdminNoticesRoute
  '/admin/posts': typeof AdminPostsRoute
  '/admin/registrations': typeof AdminRegistrationsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/updates': typeof AdminUpdatesRoute
  '/admin/users': typeof AdminUsersRoute
  '/owner/change-password': typeof OwnerChangePasswordRoute
  '/owner/complaints': typeof OwnerComplaintsRoute
  '/owner/gala': typeof OwnerGalaRoute
  '/owner/help': typeof OwnerHelpRoute
  '/owner/mobile-change': typeof OwnerMobileChangeRoute
  '/owner/new-complaint': typeof OwnerNewComplaintRoute
  '/owner/notices': typeof OwnerNoticesRoute
  '/owner/notifications': typeof OwnerNotificationsRoute
  '/owner/post': typeof OwnerPostRoute
  '/owner/profile': typeof OwnerProfileRoute
  '/owner/shared-posts': typeof OwnerSharedPostsRoute
  '/owner/updates': typeof OwnerUpdatesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/chairman': typeof ChairmanRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/login': typeof LoginRoute
  '/notices': typeof NoticesRoute
  '/owner': typeof OwnerRouteWithChildren
  '/register': typeof RegisterRoute
  '/updates': typeof UpdatesRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/change-password': typeof AdminChangePasswordRoute
  '/admin/committee': typeof AdminCommitteeRoute
  '/admin/complaints': typeof AdminComplaintsRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/help': typeof AdminHelpRoute
  '/admin/mobile-requests': typeof AdminMobileRequestsRoute
  '/admin/notices': typeof AdminNoticesRoute
  '/admin/posts': typeof AdminPostsRoute
  '/admin/registrations': typeof AdminRegistrationsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/updates': typeof AdminUpdatesRoute
  '/admin/users': typeof AdminUsersRoute
  '/owner/change-password': typeof OwnerChangePasswordRoute
  '/owner/complaints': typeof OwnerComplaintsRoute
  '/owner/gala': typeof OwnerGalaRoute
  '/owner/help': typeof OwnerHelpRoute
  '/owner/mobile-change': typeof OwnerMobileChangeRoute
  '/owner/new-complaint': typeof OwnerNewComplaintRoute
  '/owner/notices': typeof OwnerNoticesRoute
  '/owner/notifications': typeof OwnerNotificationsRoute
  '/owner/post': typeof OwnerPostRoute
  '/owner/profile': typeof OwnerProfileRoute
  '/owner/shared-posts': typeof OwnerSharedPostsRoute
  '/owner/updates': typeof OwnerUpdatesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/chairman': typeof ChairmanRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/login': typeof LoginRoute
  '/notices': typeof NoticesRoute
  '/owner': typeof OwnerRouteWithChildren
  '/register': typeof RegisterRoute
  '/updates': typeof UpdatesRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/change-password': typeof AdminChangePasswordRoute
  '/admin/committee': typeof AdminCommitteeRoute
  '/admin/complaints': typeof AdminComplaintsRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/help': typeof AdminHelpRoute
  '/admin/mobile-requests': typeof AdminMobileRequestsRoute
  '/admin/notices': typeof AdminNoticesRoute
  '/admin/posts': typeof AdminPostsRoute
  '/admin/registrations': typeof AdminRegistrationsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/updates': typeof AdminUpdatesRoute
  '/admin/users': typeof AdminUsersRoute
  '/owner/change-password': typeof OwnerChangePasswordRoute
  '/owner/complaints': typeof OwnerComplaintsRoute
  '/owner/gala': typeof OwnerGalaRoute
  '/owner/help': typeof OwnerHelpRoute
  '/owner/mobile-change': typeof OwnerMobileChangeRoute
  '/owner/new-complaint': typeof OwnerNewComplaintRoute
  '/owner/notices': typeof OwnerNoticesRoute
  '/owner/notifications': typeof OwnerNotificationsRoute
  '/owner/post': typeof OwnerPostRoute
  '/owner/profile': typeof OwnerProfileRoute
  '/owner/shared-posts': typeof OwnerSharedPostsRoute
  '/owner/updates': typeof OwnerUpdatesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/chairman'
    | '/contact'
    | '/gallery'
    | '/login'
    | '/notices'
    | '/owner'
    | '/register'
    | '/updates'
    | '/admin/audit'
    | '/admin/change-password'
    | '/admin/committee'
    | '/admin/complaints'
    | '/admin/gallery'
    | '/admin/help'
    | '/admin/mobile-requests'
    | '/admin/notices'
    | '/admin/posts'
    | '/admin/registrations'
    | '/admin/reports'
    | '/admin/updates'
    | '/admin/users'
    | '/owner/change-password'
    | '/owner/complaints'
    | '/owner/gala'
    | '/owner/help'
    | '/owner/mobile-change'
    | '/owner/new-complaint'
    | '/owner/notices'
    | '/owner/notifications'
    | '/owner/post'
    | '/owner/profile'
    | '/owner/shared-posts'
    | '/owner/updates'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/chairman'
    | '/contact'
    | '/gallery'
    | '/login'
    | '/notices'
    | '/owner'
    | '/register'
    | '/updates'
    | '/admin/audit'
    | '/admin/change-password'
    | '/admin/committee'
    | '/admin/complaints'
    | '/admin/gallery'
    | '/admin/help'
    | '/admin/mobile-requests'
    | '/admin/notices'
    | '/admin/posts'
    | '/admin/registrations'
    | '/admin/reports'
    | '/admin/updates'
    | '/admin/users'
    | '/owner/change-password'
    | '/owner/complaints'
    | '/owner/gala'
    | '/owner/help'
    | '/owner/mobile-change'
    | '/owner/new-complaint'
    | '/owner/notices'
    | '/owner/notifications'
    | '/owner/post'
    | '/owner/profile'
    | '/owner/shared-posts'
    | '/owner/updates'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/chairman'
    | '/contact'
    | '/gallery'
    | '/login'
    | '/notices'
    | '/owner'
    | '/register'
    | '/updates'
    | '/admin/audit'
    | '/admin/change-password'
    | '/admin/committee'
    | '/admin/complaints'
    | '/admin/gallery'
    | '/admin/help'
    | '/admin/mobile-requests'
    | '/admin/notices'
    | '/admin/posts'
    | '/admin/registrations'
    | '/admin/reports'
    | '/admin/updates'
    | '/admin/users'
    | '/owner/change-password'
    | '/owner/complaints'
    | '/owner/gala'
    | '/owner/help'
    | '/owner/mobile-change'
    | '/owner/new-complaint'
    | '/owner/notices'
    | '/owner/notifications'
    | '/owner/post'
    | '/owner/profile'
    | '/owner/shared-posts'
    | '/owner/updates'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  ChairmanRoute: typeof ChairmanRoute
  ContactRoute: typeof ContactRoute
  GalleryRoute: typeof GalleryRoute
  LoginRoute: typeof LoginRoute
  NoticesRoute: typeof NoticesRoute
  OwnerRoute: typeof OwnerRouteWithChildren
  RegisterRoute: typeof RegisterRoute
  UpdatesRoute: typeof UpdatesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chairman': {
      id: '/chairman'
      path: '/chairman'
      fullPath: '/chairman'
      preLoaderRoute: typeof ChairmanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notices': {
      id: '/notices'
      path: '/notices'
      fullPath: '/notices'
      preLoaderRoute: typeof NoticesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner': {
      id: '/owner'
      path: '/owner'
      fullPath: '/owner'
      preLoaderRoute: typeof OwnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/updates': {
      id: '/updates'
      path: '/updates'
      fullPath: '/updates'
      preLoaderRoute: typeof UpdatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/change-password': {
      id: '/admin/change-password'
      path: '/change-password'
      fullPath: '/admin/change-password'
      preLoaderRoute: typeof AdminChangePasswordRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/committee': {
      id: '/admin/committee'
      path: '/committee'
      fullPath: '/admin/committee'
      preLoaderRoute: typeof AdminCommitteeRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/complaints': {
      id: '/admin/complaints'
      path: '/complaints'
      fullPath: '/admin/complaints'
      preLoaderRoute: typeof AdminComplaintsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/gallery': {
      id: '/admin/gallery'
      path: '/gallery'
      fullPath: '/admin/gallery'
      preLoaderRoute: typeof AdminGalleryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/help': {
      id: '/admin/help'
      path: '/help'
      fullPath: '/admin/help'
      preLoaderRoute: typeof AdminHelpRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/mobile-requests': {
      id: '/admin/mobile-requests'
      path: '/mobile-requests'
      fullPath: '/admin/mobile-requests'
      preLoaderRoute: typeof AdminMobileRequestsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notices': {
      id: '/admin/notices'
      path: '/notices'
      fullPath: '/admin/notices'
      preLoaderRoute: typeof AdminNoticesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/posts': {
      id: '/admin/posts'
      path: '/posts'
      fullPath: '/admin/posts'
      preLoaderRoute: typeof AdminPostsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/registrations': {
      id: '/admin/registrations'
      path: '/registrations'
      fullPath: '/admin/registrations'
      preLoaderRoute: typeof AdminRegistrationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/updates': {
      id: '/admin/updates'
      path: '/updates'
      fullPath: '/admin/updates'
      preLoaderRoute: typeof AdminUpdatesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/owner/change-password': {
      id: '/owner/change-password'
      path: '/change-password'
      fullPath: '/owner/change-password'
      preLoaderRoute: typeof OwnerChangePasswordRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/complaints': {
      id: '/owner/complaints'
      path: '/complaints'
      fullPath: '/owner/complaints'
      preLoaderRoute: typeof OwnerComplaintsRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/gala': {
      id: '/owner/gala'
      path: '/gala'
      fullPath: '/owner/gala'
      preLoaderRoute: typeof OwnerGalaRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/help': {
      id: '/owner/help'
      path: '/help'
      fullPath: '/owner/help'
      preLoaderRoute: typeof OwnerHelpRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/mobile-change': {
      id: '/owner/mobile-change'
      path: '/mobile-change'
      fullPath: '/owner/mobile-change'
      preLoaderRoute: typeof OwnerMobileChangeRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/new-complaint': {
      id: '/owner/new-complaint'
      path: '/new-complaint'
      fullPath: '/owner/new-complaint'
      preLoaderRoute: typeof OwnerNewComplaintRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/notices': {
      id: '/owner/notices'
      path: '/notices'
      fullPath: '/owner/notices'
      preLoaderRoute: typeof OwnerNoticesRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/notifications': {
      id: '/owner/notifications'
      path: '/notifications'
      fullPath: '/owner/notifications'
      preLoaderRoute: typeof OwnerNotificationsRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/post': {
      id: '/owner/post'
      path: '/post'
      fullPath: '/owner/post'
      preLoaderRoute: typeof OwnerPostRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/profile': {
      id: '/owner/profile'
      path: '/profile'
      fullPath: '/owner/profile'
      preLoaderRoute: typeof OwnerProfileRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/shared-posts': {
      id: '/owner/shared-posts'
      path: '/shared-posts'
      fullPath: '/owner/shared-posts'
      preLoaderRoute: typeof OwnerSharedPostsRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/updates': {
      id: '/owner/updates'
      path: '/updates'
      fullPath: '/owner/updates'
      preLoaderRoute: typeof OwnerUpdatesRouteImport
      parentRoute: typeof OwnerRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAuditRoute: typeof AdminAuditRoute
  AdminChangePasswordRoute: typeof AdminChangePasswordRoute
  AdminCommitteeRoute: typeof AdminCommitteeRoute
  AdminComplaintsRoute: typeof AdminComplaintsRoute
  AdminGalleryRoute: typeof AdminGalleryRoute
  AdminHelpRoute: typeof AdminHelpRoute
  AdminMobileRequestsRoute: typeof AdminMobileRequestsRoute
  AdminNoticesRoute: typeof AdminNoticesRoute
  AdminPostsRoute: typeof AdminPostsRoute
  AdminRegistrationsRoute: typeof AdminRegistrationsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminUpdatesRoute: typeof AdminUpdatesRoute
  AdminUsersRoute: typeof AdminUsersRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAuditRoute: AdminAuditRoute,
  AdminChangePasswordRoute: AdminChangePasswordRoute,
  AdminCommitteeRoute: AdminCommitteeRoute,
  AdminComplaintsRoute: AdminComplaintsRoute,
  AdminGalleryRoute: AdminGalleryRoute,
  AdminHelpRoute: AdminHelpRoute,
  AdminMobileRequestsRoute: AdminMobileRequestsRoute,
  AdminNoticesRoute: AdminNoticesRoute,
  AdminPostsRoute: AdminPostsRoute,
  AdminRegistrationsRoute: AdminRegistrationsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminUpdatesRoute: AdminUpdatesRoute,
  AdminUsersRoute: AdminUsersRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface OwnerRouteChildren {
  OwnerChangePasswordRoute: typeof OwnerChangePasswordRoute
  OwnerComplaintsRoute: typeof OwnerComplaintsRoute
  OwnerGalaRoute: typeof OwnerGalaRoute
  OwnerHelpRoute: typeof OwnerHelpRoute
  OwnerMobileChangeRoute: typeof OwnerMobileChangeRoute
  OwnerNewComplaintRoute: typeof OwnerNewComplaintRoute
  OwnerNoticesRoute: typeof OwnerNoticesRoute
  OwnerNotificationsRoute: typeof OwnerNotificationsRoute
  OwnerPostRoute: typeof OwnerPostRoute
  OwnerProfileRoute: typeof OwnerProfileRoute
  OwnerSharedPostsRoute: typeof OwnerSharedPostsRoute
  OwnerUpdatesRoute: typeof OwnerUpdatesRoute
}

const OwnerRouteChildren: OwnerRouteChildren = {
  OwnerChangePasswordRoute: OwnerChangePasswordRoute,
  OwnerComplaintsRoute: OwnerComplaintsRoute,
  OwnerGalaRoute: OwnerGalaRoute,
  OwnerHelpRoute: OwnerHelpRoute,
  OwnerMobileChangeRoute: OwnerMobileChangeRoute,
  OwnerNewComplaintRoute: OwnerNewComplaintRoute,
  OwnerNoticesRoute: OwnerNoticesRoute,
  OwnerNotificationsRoute: OwnerNotificationsRoute,
  OwnerPostRoute: OwnerPostRoute,
  OwnerProfileRoute: OwnerProfileRoute,
  OwnerSharedPostsRoute: OwnerSharedPostsRoute,
  OwnerUpdatesRoute: OwnerUpdatesRoute,
}

const OwnerRouteWithChildren = OwnerRoute._addFileChildren(OwnerRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  ChairmanRoute: ChairmanRoute,
  ContactRoute: ContactRoute,
  GalleryRoute: GalleryRoute,
  LoginRoute: LoginRoute,
  NoticesRoute: NoticesRoute,
  OwnerRoute: OwnerRouteWithChildren,
  RegisterRoute: RegisterRoute,
  UpdatesRoute: UpdatesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
